global using KobzaReferee.Application.Common.Interfaces;
global using KobzaReferee.Domain.Statistics;
global using KobzaReferee.Domain.TelegramChats;
global using KobzaReferee.Domain.TelegramUsers;
global using KobzaReferee.Domain.WordGuesses;
global using KobzaReferee.Persistence.Sqlite.Configurations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
